import { env } from '$env/dynamic/private';
import { json } from '@sveltejs/kit';
import { Resend } from 'resend';
import { supabase } from '$lib/supabaseClient.js';

// Basic in-memory rate limiter (best-effort; resets on server restart / cold start).
// Blocks an IP that submits more than MAX_REQUESTS within WINDOW_MS.
const RATE_LIMIT_WINDOW_MS = 10 * 60 * 1000; // 10 minutes
const RATE_LIMIT_MAX_REQUESTS = 5;
const requestLog = new Map();

function isRateLimited(ip) {
	const now = Date.now();
	const timestamps = (requestLog.get(ip) || []).filter((t) => now - t < RATE_LIMIT_WINDOW_MS);
	timestamps.push(now);
	requestLog.set(ip, timestamps);
	return timestamps.length > RATE_LIMIT_MAX_REQUESTS;
}

const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// Verifies a Cloudflare Turnstile token with Cloudflare's siteverify endpoint.
// Requires TURNSTILE_SECRET_KEY to be set in the server environment.
async function verifyTurnstileToken(token, ip) {
	if (!env.TURNSTILE_SECRET_KEY) {
		console.error('TURNSTILE_SECRET_KEY is not set — rejecting submission.');
		return false;
	}
	if (!token) return false;

	try {
		const params = new URLSearchParams();
		params.append('secret', env.TURNSTILE_SECRET_KEY);
		params.append('response', token);
		if (ip && ip !== 'unknown') params.append('remoteip', ip);

		const res = await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify', {
			method: 'POST',
			body: params
		});
		const outcome = await res.json();
		return outcome.success === true;
	} catch (e) {
		console.error('Turnstile verification request failed:', e);
		return false;
	}
}

function validateContactPayload({ firstName, lastName, email, number, message }) {
	if (typeof firstName !== 'string' || firstName.trim().length < 3) {
		return 'First name must be at least 3 characters.';
	}
	if (typeof lastName !== 'string' || !lastName.trim()) {
		return 'Last name is required.';
	}
	if (typeof email !== 'string' || !email.trim() || !emailRegex.test(email.trim())) {
		return 'A valid email is required.';
	}
	if (typeof number !== 'string' && typeof number !== 'number') {
		return 'A valid phone number is required.';
	}
	const numberStr = String(number).trim();
	if (numberStr.length < 10) {
		return 'Phone number must be at least 10 digits.';
	}
	if (typeof message !== 'string' || message.trim().length < 10) {
		return 'Message must be at least 10 characters.';
	}
	return null;
}

export async function POST({ request, getClientAddress }) {
	const body = await request.json();
	const { firstName, lastName, email, number, message, website, turnstileToken } = body;

	// Honeypot check: "website" is a hidden field real users never see or fill in.
	// If it's populated, this is almost certainly a bot — pretend success and stop.
	if (website) {
		return json({ success: true, message: 'Message sent successfully' });
	}

	// Server-side validation. The form in +page.svelte already validates this,
	// but that check only runs in the browser — bots can (and were) hitting this
	// endpoint directly, which is how garbled spam ended up in the inbox/database.
	const validationError = validateContactPayload({ firstName, lastName, email, number, message });
	if (validationError) {
		return json({ success: false, message: validationError }, { status: 400 });
	}

	let clientIp = 'unknown';
	try {
		clientIp = getClientAddress();
	} catch (e) {
		// getClientAddress can throw in some adapters/environments; fail open on IP lookup only.
	}

	// CAPTCHA check: verifies the Cloudflare Turnstile token generated by the widget
	// on the contact form. This is the main defense against scripted/targeted bots
	// that fill in believable data and skip the honeypot.
	const isHuman = await verifyTurnstileToken(turnstileToken, clientIp);
	if (!isHuman) {
		return json(
			{ success: false, message: 'CAPTCHA verification failed. Please try again.' },
			{ status: 400 }
		);
	}

	if (isRateLimited(clientIp)) {
		return json(
			{ success: false, message: 'Too many submissions. Please try again later.' },
			{ status: 429 }
		);
	}

	try {
		const resend = new Resend(env.RESEND_API_KEY);

        const emailHtml = `
            <body style="font-family: 'Inter', 'Helvetica Neue', sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px; color: #333; line-height: 1.6;">
                <div style="background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05); overflow: hidden;">
                    <div style="padding: 32px; background-color: #f8fafc; border-bottom: 1px solid #eaeaea;">
                    <h1 style="margin: 0; font-size: 24px; font-weight: 600; color: #1a202c;">Message from ${firstName} ${lastName}</h1>
                    </div>
                    
                    <div style="padding: 32px;">
                    <div style="margin-bottom: 24px;">
                        <p style="margin: 0 0 6px; font-size: 14px; color: #718096; font-weight: 500;">Contact Information</p>
                        <p style="margin: 0 0 4px; font-size: 16px;"><strong>Email:</strong> ${email}</p>
                        <p style="margin: 0; font-size: 16px;"><strong>Phone:</strong> ${number}</p>
                    </div>
                    
                    <div style="margin-top: 24px;">
                        <p style="margin: 0 0 6px; font-size: 14px; color: #718096; font-weight: 500;">Message</p>
                        <div style="padding: 16px; background-color: #f8fafc; border-radius: 6px; font-size: 16px;">
                        ${message}
                        </div>
                    </div>
                    </div>
                    
                    <div style="padding: 20px 32px; background-color: #f8fafc; border-top: 1px solid #eaeaea; font-size: 14px; color: #718096; text-align: center;">
                    <p style="margin: 0;">This message was sent through your contact form.</p>
                    </div>
                </div>
            </body>`

        const emailText = `Message from ${firstName} ${lastName}\n\nContact Information\nEmail: ${email}\nPhone: ${number}\n\nMessage:\n${message}`;

		const { data, error } = await resend.emails.send({
			from: 'Daystar Solar <updates@daystarsolar.co.in>',
			// to: ['products@daystarsolar.co.in', 'jamalhascientist@gmail.com'],
			to: ['products@daystarsolar.co.in', 'info@daystarsolar.co.in'],
			subject: 'New Message Received from Contact Form',
			html: emailHtml,
            text: emailText,
		});

        if (error) {
            console.error('Resend send error:', error);
            throw new Error(`Failed to send email: ${error.message || error}`);
        }
        // console.log('Email sent successfully:', data);

        const { data: supabaseResult, error: supabaseError } = await supabase
            .from('contact_form') // Ensure 'reports' table exists with 'name' (text) and 'data' (jsonb) columns
            .insert([{ name: `${firstName} ${lastName}`, email: email, phone_no: number, message: message }])
            .select();

        if (supabaseError) {
            console.error('Supabase insert error:', supabaseError);
            throw new Error(`Failed to save report to database: ${supabaseError.message}`);
        }

		return json({ success: true, message: 'Message sent successfully' });
	} catch (error) {
		console.error('Error sending message:', error);
		return json(
			{ success: false, message: 'Failed to send message', error: error.message },
			{ status: 500 }
		);
	}
}
